### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by kanetjuh**
There was an error with .members and looking up and using values ​​from the .env file. I solved this by adding and modifying these three lines of code.

### CODE REVIEW

**Comment by kanetjuh** [comment]
I know it is a bit junky, but this is the only way for me it worked. I tried to console.log every env.GUILD_ID for example and it wouldn't work for me in the guilds.cache.get

I don't know if other people have the same issue but if they do this is one of the maybe many fixes.

**Comment by FivePixels** [comment]
I've continued to dig and it seems that dotenv has had a number of breaking changes that other developers have mentioned. One that clearly stands out is that previously we had to manually parse dotenv files to convert them to the primitives/data structures expected. Now it looks like dotenv does that. 

The change still should not be where you committed. The logic for parsing/loading values needs to be looked over. Right now `.parsed` only seems to be returning String values. We need to make sure that they are parsed to the correct data type/primitive. 

Here's a glimpse at the `env` object we're getting back from dotenv by default. It's probably safe to remove the `dotenv-parse-variables` dependency going forward since dotenv is trying to handle parsing. `ITEMS_DESCRIPTIONS` for example was being parsed originally as an array, (hence this check https://github.com/FivePixels/Tribble/blob/8c4dd7ab827146fff0c56d133dcca25f670e6615/index.js#L85) but now it's being parsed as a string.

`env = require('dotenv').config({ path: dev ? 'dev.env' : '.env' });`
image

**Comment by FivePixels** [comment]
Let me know if I should look into this or if you would like to take a stab at it.

**Comment by kanetjuh** [comment]
It would be nice if you also take a look, as I've tried everything but nothing really works in the bot. Like `menu.addPages()`

**Comment by FivePixels** [comment]
> It would be nice if you also take a look, as I've tried everything but nothing really works in the bot. Like `menu.addPages()`

Closing this PR and opening an issue for it

**Pull request closed without merging**
